<?php
/**
 * @file
 * Bibliographic work management for the semantic web using the Bibliographic Ontology Specification.
 */


/**
 * Implements hook_entity_info().
 */
function bibo_entity_info() {
  $entity_info = array();

  // Contributor entity information.
  $entity_info['bibo_contributor'] = array(
    // Human-readable label and description.
    'label' => t('Contributor'),
    'plural label' => t('Contributors'),
    'description' => t('Contributor to a bibliographic work.'),
    // Database table and keys.
    'base table' => 'bibo_contributor',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'bibo_contributor_id',
      'bundle' => 'type',
      'label' => 'name',
    ),
    'module' => 'bibo',
    // Bundles.
    'bundles' => array(
      'person' => array(
        'label' => t('Person'),
        'admin' => array(
          'path' => 'admin/people/contributor/person',
          'bundle argument' => 3,
          'access arguments' => array('administer bibo_contributors'),
        ),
      ),
      'organization' => array(
        'label' => t('Organization'),
        'admin' => array(
          'path' => 'admin/people/contributor/organization',
          'bundle argument' => 3,
          'access arguments' => array('administer bibo_contributors'),
        ),
      ),
    ),
    // Callbacks.
    'access callback' => 'bibo_contributor_access',
    'label callback' => 'bibo_contributor_label',
    'uri callback' => 'entity_class_uri',
    // Entity and controller classes.
    'entity class' => 'BIBOContributor',
    'controller class' => 'BIBOContributorController',
    'metadata controller class' => 'BIBOContributorMetadataController',
    'views controller class' => 'EntityDefaultViewsController',
    // Administration UI.
    'admin ui' => array(
      'path' => 'admin/people/contributor',
      'controller class' => 'BIBOContributorUIController',
      'menu wildcard' => '%bibo_contributor',
    ),
  );

  return $entity_info;
}

/**
 * Implement hook_menu().
 */
function bibo_menu() {
  // Contribution field autocomplete menu item.
  $items['bibo_contribution/autocomplete'] = array(
    'title' => 'Contribution autocomplete',
    'page callback' => 'bibo_contribution_autocomplete',
    'access callback' => 'user_access',
    'access arguments' => array('view any bibo_contributor'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function bibo_menu_alter(&$items) {
  // Hide Manage fields / Manage display on Contributors overview page.
  $items['admin/people/contributor/organization/fields']['type'] = MENU_CALLBACK;
  $items['admin/people/contributor/organization/display']['type'] = MENU_CALLBACK;
  $items['admin/people/contributor/person/fields']['type'] = MENU_CALLBACK;
  $items['admin/people/contributor/person/display']['type'] = MENU_CALLBACK;
}

/**
 * Implements hook_permission().
 */
function bibo_permission() {
  $permissions = array(
    // Contributor permissions.
    'administer bibo_contributors' => array(
      'title' => t('Administer contributors'),
      'description' => t('Edit and delete all contributors and their fields.'),
    ),
    'edit any bibo_contributor' => array(
      'title' => t('Edit any contributor.'),
    ),
    'view any bibo_contributor' => array(
      'title' => t('View any contributor.'),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_admin_paths().
 */
function bibo_admin_paths() {
  // Use administration theme on contributor 'Merge' tab.
  $paths = array(
    'contributor/*/merge' => TRUE,
  );

  return $paths;
}

/**
 * Autocomplete callback for bibo_contribution field.
 */
function bibo_contribution_autocomplete($string = '') {
  $suggestions = array();

  // Find matching contributor.
  $query = new EntityFieldQuery;
  $result = $query->entityCondition('entity_type', 'bibo_contributor')
    ->propertyCondition('name', $string . '%', 'LIKE')
    ->propertyOrderBy('name', 'ASC')
    ->range(0, 10)
    ->execute();
  if (isset($result['bibo_contributor'])) {
    $ids = array_keys($result['bibo_contributor']);
    $entities = entity_load('bibo_contributor', $ids);
    foreach ($entities as $entity) {
      $key = bibo_contributor_label($entity) . ' [' . $entity->bibo_contributor_id . ']';
      $suggestions[$key] = $key;
    }
  }
  drupal_json_output($suggestions);
}

/**
 * Validation callback to process autocomplete result.
 */
function bibo_contribution_autocomplete_validate($element, &$form_state, $form) {
  $value = '';
  if (!empty($element['#value'])) {
    // Match bibo_contributor_id from square bracket in "Name [id]".
    if (preg_match("/.+\[(\d+)\]/", $element['#value'], $matches)) {
      $value = $matches[1];
    }
    else {
      // Match bibo_contributor_id from matching name property.
      $query = new EntityFieldQuery;
      $result = $query->entityCondition('entity_type', 'bibo_contributor')
        ->propertyCondition('name', $element['#value'], '=')
        ->execute();
      if (isset($result['bibo_contributor'])) {
        if (count($result['bibo_contributor']) > 1) {
          // Found many contributors, we need exactly one.
          form_error($element, t('Multiple contributors match the specified name. Please select one from the autocomplete suggestions.'));
        }
        else {
          // Found one contributor.
          $id = array_keys($result['bibo_contributor']);
          $value = $id[0];
        }
      }
      else {
        // Found no contributor, create a new one.
        $entity = entity_create('bibo_contributor', array('name' => $element['#value']));
        if (entity_save('bibo_contributor', $entity)) {
          $value = $entity->bibo_contributor_id;
        }
        else {
          form_error($element, t('Could not create contributor %name.', array('%name' => $element['#value'])));
        }
      }
    }
  }
  // Update the value of this element so the field can validate bibo_contributor_id.
  form_set_value($element, $value, $form_state);
}

/**
 * Implements hook_field_info().
 */
function bibo_field_info() {
  $field_info = array();

  // Contribution field information.
  $field_info['bibo_contribution'] = array(
    'label' => t('BIBO Contribution'),
    'description' => t('Contributor reference with a specific role.'),
    'settings' => array(),
    'instance_settings' => array(
      'allowed_roles' => array(
        'author' => 'author',
      ),
    ),
    'default_widget' => 'bibo_contribution_widget_default',
    'default_formatter' => 'bibo_contribution_formatter_default',
  );

  return $field_info;
}


/**
 * Implements hook_field_is_empty().
 */
function bibo_field_is_empty($item, $field) {
  // Contribution field empty check.
  if ($field['type'] == 'bibo_contribution') {
    if (sizeof($item['bibo_contribution']) > sizeof(array_filter($item['bibo_contribution']))) {
      return TRUE;
    }
    return FALSE;
  }
}

/**
 * Implements hook_field_validate().
 */
function bibo_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  // Validate contribution field.
  if ($field['type'] == 'bibo_contribution') {
    foreach ($items as $delta => $item) {
      if (!bibo_field_is_empty($item, $field)) {
        // Validate existing bibo_contributor_id.
        $id = $item['bibo_contribution']['bibo_contributor_id'];
        if (empty(entity_load('bibo_contributor', array($id)))) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'bibo_contribution_invalid_id',
            'message' => t('%name: contributor does not exist (%id).', array(
              '%name' => $instance['label'],
              '%id' => $id,
            )),
          );
        }
        // Validate allowed bibo_contributor_role.
        $role = $item['bibo_contribution']['bibo_contribution_role'];
        if (empty($instance['settings']['allowed_roles'][$role])) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'bibo_contribution_invalid_role',
            'message' => t('%name: contribution role is not allowed (%role).', array(
              '%name' => $instance['label'],
              '%role' => $role,
            )),
          );
        }
      }
    }
  }
}

/**
 * Implements hook_field_presave().
 */
function bibo_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if (empty($items)) {
    return;
  }

  // Contribution field presave.
  if ($field['type'] == 'bibo_contribution' && array_key_exists('bibo_contribution', $items[0])) {
    foreach ($items as $delta => $item) {
      $items[$delta]['bibo_contributor_id'] = $item['bibo_contribution']['bibo_contributor_id'];
      $items[$delta]['bibo_contribution_role'] = $item['bibo_contribution']['bibo_contribution_role'];
    }
  }
}

/**
 * Implements hook_field_instance_settings_form().
 */
function bibo_field_instance_settings_form($field, $instance) {
  $form = array();

  // Contribution field instance settings form.
  if ($field['type'] == 'bibo_contribution') {
    $settings = $instance['settings'];
    $form['allowed_roles'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Allowed contribution roles'),
      '#options' => _bibo_get_default_contribution_roles(),
      '#default_value' => $settings['allowed_roles'],
      '#required' => FALSE,
      '#description' => t('Select the allowed roles for this particular contribution field instance.'),
    );
  }

  return $form;
}

/**
 * Helper function to build list of default contribution roles.
 */
function _bibo_get_default_contribution_roles() {
  // Default contribution roles.
  $roles = array(
    'author' => t('Author'),
    'editor' => t('Editor'),
    'translator' => t('Translator'),
    'book_author' => t('Book author'),
  );

  return $roles;
}

/**
 * Implements hook_field_widget_info().
 */
function bibo_field_widget_info() {
  $widget_info = array();

  // Contribution default widget information.
  $widget_info['bibo_contribution_widget_default'] = array(
    'label' => t('Default'),
    'field types' => array('bibo_contribution'),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
      'default value' => FIELD_BEHAVIOR_NONE,
    ),
  );

  return $widget_info;
}

/**
 * Implements hook_field_widget_form().
 */
function bibo_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $element = array();

  // Contribution default widget form.
  if ($instance['widget']['type'] == 'bibo_contribution_widget_default') {
    // Inline container for the widget.
    $element['bibo_contribution']['#prefix'] = '<div class="container-inline">';
    $element['bibo_contribution']['#suffix'] = '</div>';

    // Contributor.
    $id = isset($items[$delta]['bibo_contributor_id']) ? $items[$delta]['bibo_contributor_id'] : 0;
    $entity = entity_load('bibo_contributor', array($id));
    $entity = empty($entity) ? NULL : bibo_contributor_label($entity[$id]) . ' [' . $id . ']';
    $element['bibo_contribution']['bibo_contributor_id'] = array(
      '#type' => 'textfield',
      '#default_value' => $entity,
      '#element_validate' => array('bibo_contribution_autocomplete_validate'),
      '#autocomplete_path' => 'bibo_contribution/autocomplete',
    );

    // Contribution role.
    $roles = _bibo_get_default_contribution_roles();
    $roles = array_intersect_key($roles, array_filter($instance['settings']['allowed_roles']));
    $element['bibo_contribution']['bibo_contribution_role'] = array(
      '#type' => 'select',
      '#options' => $roles,
      '#default_value' => isset($items[$delta]['bibo_contribution_role']) ? $items[$delta]['bibo_contribution_role'] : NULL,
    );

    // Remove button.
    if ($field['cardinality'] == FIELD_CARDINALITY_UNLIMITED) {
      $element['bibo_contribution']['remove_button'] = array(
        '#type' => 'button',
        '#value' => t('Remove'),
        '#name' => drupal_html_class(
          'remove-' . $field['field_name'] . '-' . $langcode . '-' . $delta
        ),
        '#submit' => 'bibo_multivalue_item_ajax_callback',
        '#ajax' => array('bibo_multivalue_item_ajax_callback'),
        '#limit_validation_errors' => array(),
        '#field_name' => $field['field_name'],
        '#langcode' => $langcode,
        '#delta' => $delta,
        '#field_remove_item' => TRUE,
      );
    }
  }

  return $element;
}

/**
 * Implements hook_form_alter().
 *
 * This is needed to remove items from a form using the 'Remove' button.
 */
function bibo_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form_state['triggering_element']['#field_remove_item'])) {
    $field_name = $form_state['triggering_element']['#field_name'];
    $language = $form_state['triggering_element']['#langcode'];
    $delta = $form_state['triggering_element']['#delta'];
    if (!isset($form_state['#field_remove_item'])) {
      $form_state['#field_remove_item'] = array();
    }
    // Keep track of this removal.
    $form_state['#field_remove_item'][$field_name][$language][] = $delta;
  }
  // Remove all items again in case the form submission fails validation.
  if (!empty($form_state['#field_remove_item'])) {
    foreach ($form_state['#field_remove_item'] as $field_name => $field_values) {
      foreach ($field_values as $language => $field_deltas) {
        foreach ($field_deltas as $delta) {
          bibo_multivalue_item_remove_element($form, $form_state, $field_name, $language, $delta);
        }
      }
    }
  }
}

/**
 * AJAX callback for the 'Remove' button.
 */
function bibo_multivalue_item_ajax_callback(&$form, $form_state) {
  $config = bibo_multivalue_item_ajax_remove($form, $form_state);
  $wrapper = '.' . $config['wrapper'];

  // Only render the piece of form that we want depending on the parents.
  $element = $form;
  foreach ($config['array_parents'] as $name) {
    $element = &$element[$name];
    if (!empty($element[$config['field_name']])) {
      break;
    }
  }

  return array(
    '#type' => 'ajax',
    '#commands' => array(
      ajax_command_replace($wrapper, render($element[$config['field_name']])),
    ),
  );
}

/**
 * Recursively look for the elements to remove in the form array.
 */
function bibo_multivalue_item_ajax_remove(&$element, &$form_state) {
  $config = array();

  $children = element_children($element);
  if (count($children)) {
    foreach ($children as $childname) {
      if (isset($element['#field_remove_item']) && in_array($childname, array_keys($form_state['#field_remove_item']))) {
        return array(
          'array_parents' => $element['#array_parents'],
          'wrapper' => $element['#field_remove_item']['wrapper'],
          'field_name' => $element['#field_remove_item']['field_name'],
        );
      }
      $config = bibo_multivalue_item_ajax_remove($element[$childname], $form_state);
    }
  }

  return $config;
}

/**
 * Remove the field items recursively.
 */
function bibo_multivalue_item_remove_element(&$element, &$form_state, $field_name, $language, $delta) {
  $children = element_children($element);
  if (count($children)) {
    foreach ($children as $childname) {
      if (is_array($element[$childname])) {
        bibo_multivalue_item_remove_element($element[$childname], $form_state, $field_name, $language, $delta);
      }
      if ($childname === $field_name) {
        $element['#field_remove_item'] = array(
          'wrapper' => $element[$field_name]['#attributes']['class'][1],
          'field_name' => $field_name,
        );
        // Remove field item.
        unset($element[$field_name][$language][$delta]);
      }
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function bibo_field_formatter_info() {
  // Contribution default formatter information.
  $formatter_info['bibo_contribution_formatter_default'] = array(
    'label' => t('Default'),
    'field types' => array('bibo_contribution'),
    'settings' => array(
      'name_format' => 'full_name',
      'display_link' => TRUE,
      'display_role' => TRUE,
    ),
  );

  return $formatter_info;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function bibo_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  // Contribution default formatter settings form.
  if ($display['type'] == 'bibo_contribution_formatter_default') {
    // Name format
    $element['name_format'] = array(
      '#title' => t('Name format'),
      '#type' => 'select',
      '#options' => array(
        'abbreviated_name' => t('Abbreviated name'),
        'full_name' => t('Full name'),
      ),
      '#default_value' => $settings['name_format'],
    );
    // Link to contributor.
    $element['display_link'] = array(
      '#title' => t('Link to contributor'),
      '#type' => 'checkbox',
      '#default_value' => $settings['display_link'],
    );
    // Display / Hide role.
    $element['display_role'] = array(
      '#title' => t('Display contribution role'),
      '#type' => 'checkbox',
      '#default_value' => $settings['display_role'],
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function bibo_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $name_formats = array(
    'abbreviated_name' => t('Abbreviated name'),
    'full_name' => t('Full name'),
  );
  $summary = array();

  // Contribution default formatter settings summary.
  if ($display['type'] == 'bibo_contribution_formatter_default') {
    $summary[] = 'Name format: ' . $name_formats[$settings['name_format']];
    $summary[] = $settings['display_link'] ? t('Display link') : t('No link');
    $summary[] = $settings['display_role'] ? t('Display role') : t('Hide role');
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function bibo_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  // Contribution default formatter view.
  if ($display['type'] == 'bibo_contribution_formatter_default') {
    $roles = _bibo_get_default_contribution_roles();
    foreach ($items as $delta => $item) {
      $id = $item['bibo_contributor_id'];
      $bibo_contributor = entity_load('bibo_contributor', array($id));
      if (!empty($bibo_contributor)) {
        // Name format.
        switch ($display['settings']['name_format']) {
          case 'abbreviated_name':
            $item_output = $bibo_contributor[$id]->name;
            break;
          case 'complete_name':
          default:
            $item_output = bibo_contributor_label($bibo_contributor[$id]);
            break;
        }
        // Link to contributor.
        if ($display['settings']['display_link']) {
          $item_output = l($item_output, entity_uri('bibo_contributor', $bibo_contributor[$id])['path']);
        }
        // Display role.
        if ($display['settings']['display_role']) {
          $role = $item['bibo_contribution_role'];
          $item_output .= ' (' . $roles[$role] . ')';
        }
        $element[$delta]['bibo_contribution_row']['content'] = array(
          '#markup' => $item_output,
        );
      }
    }
  }

  return $element;
}

/**
 * Implements hook_views_api().
 */
function bibo_views_api($module = NULL, $api = NULL) {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'bibo') . '/views',
  );
}

/**
 * Include all files here to prevent undefined functions.
 */
module_load_include('inc', 'bibo', 'bibo_contributor');
