<?php

/**
 * Implements hook_entity_info_alter().
 */
function bibo_apa_entity_info_alter(&$entity_info) {
  $entity_info['bibo_work']['view callback'] = 'bibo_apa_view_callback';
  $entity_info['bibo_work']['view modes']['citation'] = array(
    'label' => t('Citation'),
    'custom settings' => FALSE,
  );
  $entity_info['bibo_work']['view modes']['reference'] = array(
    'label' => t('Reference'),
    'custom settings' => FALSE,
  );
}

/**
 * Helper function to intercept bibo_apa view modes.
 */
function bibo_apa_view_callback($entities, $view_mode = 'full', $langcode = NULL, $page = NULL) {
  // Don't interfere with default view mode.
  if ($view_mode == 'default' || $view_mode == 'full') {
    return entity_get_controller('bibo_work')->view($entities, $view_mode, $langcode, $page);
  }
  // Prepare APA view mode.
  $entities = entity_key_array_by_property($entities, 'bibo_work_id');
  field_attach_prepare_view('bibo_work', $entities, $view_mode);
  entity_prepare_view('bibo_work', $entities);
  $langcode = isset($langcode) ? $langcode : $GLOBALS['language_content']->language;

  $view = array();
  foreach ($entities as $entity) {
    $build = array(
      '#theme' => 'bibo_apa',
      '#entity' => $entity,
      '#view_mode' => $view_mode,
      '#language' => $langcode,
    );
    // Allow modules to modify the structured entity.
    $key = isset($entity->bibo_work_id) ? $entity->bibo_work_id : NULL;
    $view['bibo_work'][$key] = $build;
  }
  return $view;
}

/**
 * Implements hook_theme().
 */
function bibo_apa_theme() {
  return array(
    'bibo_apa' => array(
      'file' => 'bibo_apa.module',
      'variables' => array(
        'entity' => '',
        'build' => '',
        'view_mode' => '',
        'language' => '',
      ),
    ),
  );
}

/**
 * Implements theme_HOOK().
 */
function theme_bibo_apa($variables) {
  $entity = $variables['entity'];

  $authors = _bibo_apa_get_contributors_by_role($entity, 'author');
  
  return 'BIBO APA reference';
}

function _bibo_apa_get_contributors_by_role($entity, $role) {
  $contributors = array();

  if (isset($entity->bibo_contributors[LANGUAGE_NONE])) {
    foreach ($entity->bibo_contributors[LANGUAGE_NONE] as $contributor) {
      if ($contributor['bibo_contribution_role'] == $role)
        $contributors[] = $contributor;
    }
  }

  return $contributors;
}
